import { Metadata } from "next";
import localFont from "next/font/local";
import Script from 'next/script';
// import headingfonts from "../public/assets/fonts";

// CSS imports
import "../public/assets/css/bootstrap.min.css";
import "../public/assets/css/fontawesome.min.css";
import "../public/assets/css/venobox.min.css";
import "../public/assets/css/animate.min.css";
import "../public/assets/css/carouselTicker.css";
import "../public/assets/css/keyframe-animation.css";
import "../public/assets/css/odometer.min.css";
import "../public/assets/css/nice-select.css";
import "../public/assets/css/swiper.min.css";
import "../public/assets/css/main.css";
// import "../public/assets/css/main.css.map";

// Font imports

const geistSans = localFont({
 src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

// const prixsans = headingfonts({
// src: "../public/assets/fa-brands-400.ttf",
// });

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata
export const metadata: Metadata = {
  title: "webspace studio",
  description: "Generated by create next app",
};

// RootLayout Component
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        {children}

        <Script src="https://code.jquery.com/jquery-3.6.0.min.js" strategy="beforeInteractive" />

        <Script src="/assets/js/vendor/bootstrap-bundle.js" strategy="afterInteractive" />
        <Script src="/assets/js/vendor/imagesloaded-pkgd.js" strategy="afterInteractive" />
        <Script src="/assets/js/vendor/waypoints.min.js"  strategy="afterInteractive"  />
        <Script src="/assets/js/vendor/venobox.min.js"  strategy="afterInteractive" />
        <Script src="/assets/js/vendor/odometer.min.js" strategy="afterInteractive"  />
        <Script src="/assets/js/vendor/meanmenu.js"  strategy="afterInteractive" />
        <Script src="/assets/js/vendor/jquery.isotope.js" strategy="afterInteractive"  />
        <Script src="/assets/js/vendor/wow.min.js"  strategy="afterInteractive" />
        <Script src="/assets/js/vendor/swiper.min.js"  strategy="afterInteractive" />
        <Script src="/assets/js/vendor/split-type.min.js" strategy="afterInteractive"  />
        <Script src="/assets/js/vendor/gsap.min.js"  strategy="afterInteractive" />
        <Script src="/assets/js/vendor/scroll-trigger.min.js" strategy="afterInteractive"  />
        <Script src="/assets/js/vendor/scroll-smoother.js" strategy="afterInteractive"  />
        <Script src="/assets/js/vendor/jquery.carouselTicker.js" strategy="afterInteractive"  />
        <Script src="/assets/js/vendor/nice-select.js"  strategy="afterInteractive" />
        <Script src="/assets/js/ajax-form.js"  strategy="afterInteractive" />
        <Script src="/assets/js/slider.js"  strategy="afterInteractive" />
        <Script src="/assets/js/contact.js" strategy="afterInteractive"  />
        <Script src="/assets/js/main.js"  strategy="afterInteractive" />

      </body>
    </html>
  );
}
